### PR TITLE
Improve show methods

### LINKED ISSUE #341: Update `show()` method to enable plotting of discrete data (e.g. labels) using legend rather than colormap
**Is your feature request related to a problem? Please describe.**
At the moment, the `show()` method is used to plot values on top of a map using a colorbar e.g. confidence scores:
image

This method works well if your data is continuous. However, is confusing if you are plotting discrete data e.g. labels
image

**Describe the solution you'd like**
We should add an option to plot discrete values with a legend instead of colormap. 
Ideally this could just be an arg like `discrete=True` to force the plots to use a legend vs colormap.

**Describe alternatives you've considered**
Make it clear in the docs that this is whats going on.

### PR DESCRIPTION
**Pull request by rwood-97**
### Summary

Currently we have some very basic "show" methods for veiwing results. This is good for a quick look but would be better if we had some more advanced tools for visualising our results as part of the MapReader library.

Fixes #341 
Address #478 - removed the utils.py file from annotate

### Describe your changes
- Updates the show methods in `images.py`, `runner_base.py` and `rec_runner_base.py` and adds `explore_xx` methods in each of these classes. Explore uses [geopandas explore](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.explore.html) to create an interactive visualisation of results.
- Also adds a `check_georeferencing` method ot the runners as this is needed to ensure we can convert to geo coords and therefore use the explore methods.
- Adds `infer_coords_from_patches` method in images.py which uses patches to infer parent coords. This is for e.g. if you have loaded patches via the `load_patches` method and only added patch metadata (e.g. predictions). 
- Updates the way in which metrics are stored in `classifier.py` - now instead of `train_loss_epoch` and `train_fscore_epoch` as the key for a dict, we have nested dict with keys of `train`, `val`, etc and then within that keys of `loss`, `fscore` etc.  
- This enables simplification of the `plot_metrics` method, users now pass a list of metrics to plot (e.g. "loss", "fscore_micro", etc) and it will plot by default all phases. Can tell it just to plot for one phase by passing the `phases` argument. 
- I moved initialise model to the top of the file because it made sense to be grouped with the initialise_optimiser, initialise_scheduler etc methods. 

Using the `show_patches` method:

image

Using the `explore_patches` method:

image
image

Using `explore_predictions` method (i.e. the equivalent to `explore_patches` but for text spotting):

image

### Checklist before assigning a reviewer (update as needed)

- [x] Self-review code
- [x] Ensure submission passes current tests
- [x] Add tests
- [x] Update relevant docs
- [x] Update changelog

### Reviewer checklist

Please add anything you want reviewers to specifically focus/comment on.

- [ ] Everything looks ok?

### CODE REVIEW

**Comment by kallewesterling** [comment]
I really like this PR, @rwood-97. Haven't had time/been able to test run it yet. Do you need me to do that?

**Comment by rwood-97** [comment]
@kallewesterling I've updated the docs and two of the worked examples. 
Could you potentially run the worked examples to check it all works

Maybe if you have time an ideal thing would be to use the docs to write an example of `show_xx` and `explore_xxx` methods (even if just getting up to that point in the worked examples I've updated and then writing your own cells instead of running the ones I've written if that makes sense.

Let me know what you have time for and I could potentially get @thobson88 or @kmcdono2 to check it.

**Comment by kallewesterling** [comment]
> @kallewesterling I've updated the docs and two of the worked examples. Could you potentially run the worked examples to check it all works
> 
> Maybe if you have time an ideal thing would be to use the docs to write an example of `show_xx` and `explore_xxx` methods (even if just getting up to that point in the worked examples I've updated and then writing your own cells instead of running the ones I've written if that makes sense.
> 
> Let me know what you have time for and I could potentially get @thobson88 or @kmcdono2 to check it.

Sorry for the late response! I'll check it out and will test run things.

I'll also use the docs to write an example of the `show_xx` and `explore_xxx` methods!

**Comment by kallewesterling** [comment]
Otherwise, looking good!

**Comment by kallewesterling** [comment]
@rwood-97 Where in the docs do you think we should add the parts about these methods? As a new section under the [post-processing](https://mapreader.readthedocs.io/en/latest/using-mapreader/step-by-step-guide/5-post-process.html) step?

**Comment by kallewesterling** [comment]
Oh, I see now that you've already added the methods to the documentation. Can you let me know what you need me to do with the docs, then, @rwood-97 ?

**Comment by rwood-97** [comment]
I think just have a quick look and check it makes sense would be ideal, otherwise I think this is good to merge

**Review by kallewesterling — APPROVED** [review]

**Comment by kallewesterling** [comment]
Wiho!! MERGED!!

**Pull request merged**
