### PR TITLE
509 ignore blank patches

### LINKED ISSUE #509: Suggestion: Ignore patches that are completely empty
**Is your feature request related to a problem? Please describe.**
Many georeferenced maps will be oriented at an angle, while the entire file itself is rectangular. When patches are created, this can result in patches that are completely empty--all pixels are "no value". Skipping these patches altogether could speed up the patchify process (and everything that comes later).

image

```
map.patchify_all(method="pixel", patch_size=1000)
```

image

**Describe the solution you'd like**
I'm wondering if there would be any negative downstream effects of simply skipping these patches during the patchifyl process, so that they are not processed. For example, a check [here](https://github.com/maps-as-data/MapReader/blob/main/mapreader/load/images.py#L1280) could just skip the save and add_to_parent operations if a patch only has no data values in it (checking for what is truly "no data" would be the tricky part, but that should be in the metadata of the file, I think...).

**Additional context**
May be best to have this as a flag in the patchify_all() method.

GeoTIFF (COG) shown above:
[alexandria_la_1896_p3_1__jwYGc9_00.zip](https://github.com/user-attachments/files/17231567/alexandria_la_1896_p3_1__jwYGc9_00.zip)

### PR DESCRIPTION
**Pull request by mradamcox**
### Summary

This PR adds a boolean flag `skip_blank_patches` to `patchify_all()` (which is passed to `_patchify_by_pixel()`) that allows users to ignore patches that are entirely blank, i.e. all pixels within the patch have a value of 0.

Default value of the flag is `False` so that existing behavior will stay the same.

Fixes #509 

### Describe your changes

The evaluation on the patch is simple, it just uses pillow's [Image.get_bbox()](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.getbbox) and if None is returned the patch is assumed "empty".

I've added a pair of tests and images to test against, one RGB and one RGB with an alpha channel. The latter may not really be necessary... I realized that even if the map image has a "valid" patch that is all black (for example, a patch that is not around the collar because of a tilted image, but just within a black spot in the middle of the map), then that patch won't be useful for text-spotting anyway and can safely be skipped.

### Checklist before assigning a reviewer (update as needed)

- [x] Self-review code
- [x] Ensure submission passes current tests
- [x] Add tests
- [x] Update relevant docs
- [x] Update changelog

I'll set this to draft for now, and can add the docs and changelog once we confirm everything looks good and this is the right approach.

### Reviewer checklist

Please add anything you want reviewers to specifically focus/comment on.

- [ ] Everything looks ok?

### CODE REVIEW

**Comment by rwood-97** [comment]
Hi, I noticed some of our tests weren't running on your PR so I've just updated the triggers for some of our workflows. Could you merge main to pull these updates in and hopefully all tests will run now

**Comment by mradamcox** [comment]
Ok I've rebased main into this branch.

**Review by kallewesterling — COMMENTED** [review]
This looks simple enough of an edit to me, and seems to contribute great functionality. I'll let @rwood-97 do the formal approve/request changes, but LGTM! Thank you so much for the contribution, @mradamcox!

**Review by rwood-97 — APPROVED** [review]
I made one minor update just where something had been missed from the docs but otherwise looks great

**Pull request merged**
